name = "jm-pro"
main = "src/index.js"
compatibility_date = "2025-05-01"

[[d1_databases]]
binding = "DB"
database_name = "jm_pro_db"          # 注意要改成这个
database_id = "ba046623-fccc-42a1-8b83-c321b1d58940"

[vars]
ENV = "production"
